apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcastcache
  namespace: terra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcastcache
  template:
    metadata:
      labels:
        app: hazelcastcache
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
        - name: hazelcastcache
          image: prakashsharma91/hazelcastcache
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: TCP
            - name: "hz"
              containerPort: 5701
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcastcache-service
  namespace: terra
spec:
  type: NodePort
  selector:
    app: hazelcastcache
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "hz"
      port: 5701
      targetPort: 5701
